### ISSUE TITLE
MQTT-sync

### ISSUE THREAD

**Issue by mozzhead164** [atuline/ESP8266-FastLED#1]
@atuline, sorry to post this as an issue on github but thought it ok as this code is no longer supported   

I know that you have stopped developing with FastLED+MQTT but I was intrigued as to how far you got with MQTT-sync? 

I have a project involving two ESP32’s (each using 16 output level shifting shields from Jason coon) for a grand total of 32x120 (~4000) pixels on the walls of a media room for the kids. 

I can load the same sketch on each ESP easily and control them via MQTT on a RPi based Nodered dashboard.

I can map noise and spread across palettes etc but when I run a (simple) example like cylon, I obviously get two sets of cylons. 
Out of sync. You get my drift.

I was thinking to declare the full set of pixels on each controller and just show the part of the ‘screen’ that processor is governing. But that seems like a waste of resources, even-though the ESP32 has plenty.

 Is there a better way to do this while keeping the two mcu’s time coded with MQTT?

There is a Ubiquiti UniFi AP about 15ft away so connectivity shouldn’t be a problem, but would constant time sync data flood the network? Or would this all have to be on its own private network? I could also set a wireless VLAN which would keep traffic separate. 

Just seeking some advice really from a guy who’s been around the block with all this type of stuff.

Just as a side - I’ve seen you’ve migrated to WLED because of the nature of your projects. I still haven’t dipped my toe into WLED but was wondering if I need to modify some of my other projects to be more processor parallel and synced instead of fewer processors doing all work. I’ve had a lot of problems with longer cable runs etc and flickering/artefacts. What is your transition experience between the two platforms? I’m really looking forward to parallel support in WLED so I can integrate it into HomeAssistant :)

**Comment by atuline** [comment]
Hi mozz. . .

Timing was indeed an issue for me, as millis() was out of sync for those Cylon animations and I never got around to implementing NTP clients back in the day. My 'back then' solution was to reboot simultaneously, which worked about 30% of the time. The other issue I had with straight FastLED was the well known interrupt problems (I wasn't using the samguyer fork). Then, there were the MQTT clients, with Pubsubclient being the most popular, but also problematic. When the ESP lost contact with the MQTT broker, the animations stuttered, so I used an asynchronous client. Better, but not perfect.

I then had another look at the latest version of WLED. Although I've found WLED to be kind of bloated, there were several factors which sold me on the platform (and I have about 40 lanterns, but nothing as large as yours).

- It has a lot of sync protocols including MQTT (which I'm not using these days).
- It had an Android discovery application
- It supported UDP synch and you could define the UDP ports and thus have multiple groups.
- It supported an extensive web interface
- As I recall, the Cylon animations WERE in sync when you pushed the sync button.
- And so on. . .

The difficulty I had with the transition was that WLED uses the NeoPixel Library for DMA transfer of information to the LED's, so although I can use a considerable amount of my FastLED routines, I can't directly access leds[location], but have to use a lossy NeoPixel library version. It has, however removed my need to worry about the communication protocols, so I can focus on sound reactivity and FastLED (ish) routines.
